class Config :
    modelSavePath = "../checkpoints/"
    plotSavePath = "../plots/"
    fileFormat = ".conllu"
    trainTag = "-train"
    testTag = "-test"
    validationTag = "-dev"
    dataPath = "../datasets/"
    classLabels = {'ADJ' : 0, 'ADP' : 1, 'ADV' : 2, 'AUX' : 3, 'CCONJ' : 4, 'DET' : 5, 'INTJ' : 6, 'NOUN' : 7, 'NUM' : 8, 'PART' : 9, 'PRON' : 10, 'PROPN' : 11, 'PUNCT' : 12, 'SCONJ' : 13, 'SYM' : 14, 'VERB' : 15, 'X' : 16}
    classes = ['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X']
    specialTokens = {'<unknown>', '<start>', '<end>'}
    previousContextSize = 3
    futureContextSize = 3
    epochs = 15
    miniBatchSize = 32
    validationFrequency = 3
    hiddenLayers = [64]
    stackSize = 2
    hiddenStateSize = 32
